name: PR Summary Check

on:
  pull_request:
    types: [opened]

jobs:
  check-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description for certain words
        uses: actions/github-script@v6
        with:
          script: |
            const summary = context.payload.pull_request.body || "";
            const headings = ["## Problem", "## Solution", "## Testing"];
            const lines = summary.split(/\r?\n/);

            for (const heading of headings) {
              const index = lines.findIndex(line => line.trim() === heading);
              if (index === -1 || index === lines.length - 1 || !lines[index + 1].trim()) {
                core.setFailed(`PR description must contain ## Problem, ## Solution, and ## Testing, and followed by details in next lines.`);
                return;
              }
            }
            console.log("PR description is valid.");
